### ISSUE TITLE
bug: sometime @pm2/js-api does not auto refresh his tokens

### ISSUE THREAD

**Issue by shubs** [keymetrics/pm2-io-js-api#41]
@Unitech commented on [Wed May 23 2018](https://github.com/keymetrics/pm2-io-frontend/issues/119)

Sometime when I come back to the interface 6 hours later, it seems that the access_token does not get refreshed automatically and I get many Unauthorized alerts:

![image](https://user-images.githubusercontent.com/757747/40413635-9a4d8d9e-5e76-11e8-9016-43ab869db7fd.png)

**Comment by vmarchaud** [comment]
Duplicate https://github.com/keymetrics/pm2-io-js-api/issues/29

**Comment by BenoitZugmeyer** [comment]
I guess it is, every time I wakeup my laptop in the morning I have the issue. I can try to debug it next time if you want.

**Comment by Eywek** [comment]
So, as we said it's only a display problem because the frontend is using an axios middleware (cf. https://github.com/keymetrics/pm2-io-frontend/blob/development/src/utils/pm2Io.js#L32). In fact, pm2-io-js-api is trying to refresh access_token if API is returning a 401 (cf. https://github.com/keymetrics/pm2-io-js-api/blob/master/src/network.js#L146)
